In [69]:
a = [0,1,2,3,4,5,0,1,2,3,4,5,0]
b = a.copy()
b.reverse()
def test(h, group):
    gpcnt = int(h/4)
    end = 6 + group
    start = end - gpcnt
    print(end)
    interval = list(range(start, end))
    interval.reverse()
    print(interval)
    delta = 0
    def ll(idx):
        nonlocal delta
        rtn = [b[i] for i in range(idx,idx +gpcnt)]
        rtn.reverse()
        delta = delta + 1
        return  rtn
    return list(map(ll, interval))
test(8, 2)


8
[7, 6]


[[4, 5], [5, 0]]

In [34]:
 [b[i] for i in range(0,3)]

[0, 5, 4]

In [39]:
b

[0, 5, 4, 3, 2, 1, 0, 5, 4, 3, 2, 1, 0]

In [49]:
list(range(1,5, -1))

[]

In [2]:
import torch
from torch import tensor

In [33]:
import torch
from torch import tensor
x = torch.arange(1., 21).flip(0)
y = x.unfold(0,4,1)
flipped = x.unfold(0,4,1).flip([0,1])
torch.vmap(lambda v: tensor(v), 1, 1)(flipped)

AttributeError: module 'torch' has no attribute 'vmap'

In [4]:
y.tolist()

[[1.0, 2.0, 3.0, 4.0],
 [3.0, 4.0, 5.0, 6.0],
 [5.0, 6.0, 7.0, 8.0],
 [7.0, 8.0, 9.0, 10.0],
 [9.0, 10.0, 11.0, 12.0],
 [11.0, 12.0, 13.0, 14.0],
 [13.0, 14.0, 15.0, 16.0],
 [15.0, 16.0, 17.0, 18.0]]

In [6]:
torch.tensor(35)#.unfold(0,1,2)

tensor(35)

In [15]:
y[0:2, 0:2]

tensor([[1., 2.],
        [3., 4.]])

In [12]:
a=[1,2,3]
b=torch.Tensor(a)
b.reshape([1,1,3,1]).reshape([3])

tensor([1., 2., 3.])

In [11]:
import pandas as pd
import pickle
import torch

def f():
    return pd.DataFrame({"a":[1,2,3], "b":[4,5,6]})

def tf_to_int(v):
    if v:
        return 1.0
    else:
        return 0.0

def f2():
    with open('g:\coldfar_py\data_pickled\es_data_001_smallbox.df_p_c.pickle', 'rb') as f:
        df = pickle.load(f).astype({'if_highly_overlapped': 'bool'})
        df.reset_index(inplace=True)
        #df["volume"] = df["volume"].apply(lambda v: float(v))
        #df["DIF_mean_Δ"] = df["DIF_mean_Δ"].apply(lambda v: float(v))
        #df["OSC_mean_Δ"] = df["OSC_mean_Δ"].apply(lambda v: float(v))
        #df["g"] = df["g"].apply(lambda v: float(v))
        #df["if_highly_overlapped"] = df["if_highly_overlapped"].apply(lambda v: tf_to_int(v))
        #df["if_highly_overlapped"] = df["if_highly_overlapped"].apply(lambda v: str(v))
        
        return df
 
def unfold(l, shape, dimension, size, step):
    t_base = torch.Tensor(l)
    print(t_base)
    t = t_base.reshape(shape)
    print(t)
    f = t.unflod(dimension, size, step)
    return f

In [2]:
print(torch.__version__)

1.10.1+cpu


In [1]:
import torch

In [16]:
import numpy as np
np.prod([1,2,3,4])


24

In [52]:
import torch.nn.functional as F
source = torch.arange(10).unfold(0,3,1)
# now we expand to size (7, 11) by appending a row of 0s at pos 0 and pos 6, 
#and a column of 0s at pos 10
result = F.pad(input=source, pad=(0,0, 1,0), mode='constant', value=0)
source, result

(tensor([[0, 1, 2],
         [1, 2, 3],
         [2, 3, 4],
         [3, 4, 5],
         [4, 5, 6],
         [5, 6, 7],
         [6, 7, 8],
         [7, 8, 9]]),
 tensor([[0, 0, 0],
         [0, 1, 2],
         [1, 2, 3],
         [2, 3, 4],
         [3, 4, 5],
         [4, 5, 6],
         [5, 6, 7],
         [6, 7, 8],
         [7, 8, 9]]))